vich_uploader:
    db_driver: orm
    mappings:
        pictures:
            # chemin à ajouter aux fichiers pour l’appli web
            uri_prefix: 'profiles/pictures'
            # repertoire qui stocke les fichiers
            upload_destination: '%kernel.project_dir%/public/profiles/pictures'
            # remplacer le nom du fichier par un identifiant unique
            namer: vich_uploader.namer_uniqid
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
